/**
 * `{harness}-flaky-backfill.json` — the committed history behind `flaky.html`'s
 * two charts, and the rule for joining it to the live artifact.
 *
 * The page reads `{harness}-issues.json`, a 21-day aggregate, so its charts are
 * 21 days wide. Neither question the charts exist to answer fits in 21 days: the
 * flaky rate's movement is months-scale (measured on the published aggregates,
 * xpcshell went from 3,586 flaky tests on 2026-04-14 to 881 on 2026-07-14) and
 * the tree's total test count only visibly grows over months (4,531 on
 * 2025-12-15 to 4,779 on 2026-07-15, +5.5%).
 *
 * So `tools/build-flaky-backfill.ts` walks the pushdate index back over the
 * retention window and commits the four numbers per day the charts need. That
 * file is the *older* part of the series and the live artifact is the newer part;
 * this module holds the shape they share and the merge between them.
 *
 * ## The merge rule, and why the overlap is checked rather than trusted
 *
 * Union of dates, **live wins** on any date both cover, and a disagreement is
 * reported. The same three rules `mergeBackfillStats` follows in
 * `site/index-view.ts`, for the same reason: an overlap is the only place the
 * two sources can be compared, so silently preferring one throws away the single
 * check available on whether the backfill is describing the same world.
 *
 * Live wins because it is the freshest generation of that date. The backfill is
 * regenerated by hand; the artifact is regenerated nightly.
 *
 * **The two are expected to differ slightly, and the reason is the noise
 * filter.** `lib/query/flakiness.ts`'s filter reads a test's failures over the
 * whole window, so a date's classification depends on which 21 days surround it.
 * The backfill's window for a date and the live file's window for the same date
 * are different 21 days unless the end dates coincide. Measured on two published
 * xpcshell aggregates that share 19 dates (2026-02-09 and 2026-02-11): the flaky
 * count differs on 15 of them, by 0–24 tests, median 2 — worst 2026-01-23, 1719
 * against 1797, 4.5%. A caller therefore wants the disagreements *reported with
 * their size*, not treated as pass/fail: a few tests is the filter breathing, and
 * a few hundred would be a decoding bug.
 */

/** One day of the committed history: four integers and the date they describe. */
export interface FlakyBackfillRow {
    /** `YYYY-MM-DD`. */
    date: string;
    /** Tests that failed at least once that day. */
    flaky: number;
    /** Tests that passed everywhere and were skipped nowhere. */
    stable: number;
    /** Tests that did not fail but were skipped somewhere. `run-if` excluded. */
    skipped: number;
    /** `flaky + stable + skipped` — the tests that ran or were skipped. */
    total: number;
}

/** What the committed file records about how it was built. */
export interface FlakyBackfillMetadata {
    harness: string;
    startDate: string;
    endDate: string;
    /** `days.length`, so a reader does not have to count. */
    days: number;
    /**
     * The length of the window each day was classified over.
     *
     * Recorded because the noise filter's answer depends on it, so a backfill
     * built from 7-day windows would not be joinable to a page reading 21-day
     * ones. `mergeFlakyBackfill` does not enforce it — the page's own window is
     * whatever artifact it loaded — but a mismatch is worth being able to see.
     */
    windowDays: number;
    /** The noise threshold applied, so the page can say it matches its own. */
    minWindowFailures: number;
    generatedAt: string;
    /** Each source aggregate's `endDate`, oldest first. */
    sourceWindows: string[];
}

export interface FlakyBackfillFile {
    metadata: FlakyBackfillMetadata;
    /** One row per date, oldest first, no date repeated. */
    days: FlakyBackfillRow[];
}

/**
 * The window length the backfill is built with, in days.
 *
 * 21 because that is what `{harness}-issues.json` is, and the noise filter makes
 * the window length part of the classification: `MIN_FILTERABLE_DAYS` records
 * that 2026-08-04 reads 923 flaky inside a 21-day window and 562 as a
 * standalone day, a 39% gap. Backfilling with any other window length would put
 * a step at the seam that is an artefact of the tool rather than a fact about
 * the tree.
 */
export const BACKFILL_WINDOW_DAYS = 21;

/** One date the backfill and the live artifact read differently. */
export interface FlakyBackfillDisagreement {
    date: string;
    /** Which counter differs. */
    key: 'flaky' | 'stable' | 'skipped' | 'total';
    backfill: number;
    live: number;
}

/** What `mergeFlakyBackfill` produced, and what it noticed on the way. */
export interface FlakyBackfillMerge<Day> {
    /** The joined series, oldest first. */
    days: Day[];
    /** How many days came from the backfill alone. */
    backfilled: number;
    /** Dates both sources cover. */
    overlapping: number;
    /** Every counter the two disagree about, on an overlapping date. */
    disagreements: FlakyBackfillDisagreement[];
}

/** The counters the merge compares, in a fixed order for stable output. */
const KEYS = ['flaky', 'stable', 'skipped', 'total'] as const;

/**
 * Joins the committed history to the live series.
 *
 * Generic over the live day type so the page can keep whatever it already has
 * on a live day — `FlakyDay` carries a `day` index the backfill has no
 * equivalent for — while a backfilled day is built by `makeDay`. That keeps this
 * function free of any opinion about what a day *is* beyond the four counters
 * and the date, which is the only part the two sources share.
 *
 * `live` wins on a shared date.
 *
 * **The union is sorted as a whole, not concatenated as two blocks**, and that is
 * a fix rather than a preference. The first version appended the live series after
 * the backfilled days on the reasoning that a backfill is by definition older —
 * and it is not. The committed file is regenerated on its own schedule, so it can
 * end *after* the artifact the page loaded: measured on the mochitest pair here,
 * backfill 2026-01-28..2026-08-08 against a live window ending 2026-07-15, which
 * left 24 backfilled dates newer than the whole live block. Concatenating put
 * them before it, and the chart's x axis read `… 07-22, 08-05, 07-05 …` — an axis
 * that runs backwards in the middle, which is the one thing a time series must
 * never do. Sorting the union cannot express that state.
 *
 * `day` is then assigned from the sorted position, so the joined series' indexes
 * run 0..n-1 oldest-first whatever either input's own numbering was — which is
 * what `runningAverage` and every chart label walk.
 */
export function mergeFlakyBackfill<Day extends FlakyBackfillRow>(
    backfill: readonly FlakyBackfillRow[] | null,
    live: readonly Day[],
    makeDay: (row: FlakyBackfillRow, index: number) => Day
): FlakyBackfillMerge<Day> {
    const sorted = (days: readonly Day[]): Day[] =>
        [...days].sort((a, b) => a.date.localeCompare(b.date));
    if (backfill === null || backfill.length === 0) {
        return {
            days: sorted(live),
            backfilled: 0,
            overlapping: 0,
            disagreements: [],
        };
    }

    const liveByDate = new Map(live.map((day) => [day.date, day]));
    const disagreements: FlakyBackfillDisagreement[] = [];
    let overlapping = 0;
    const fromBackfill: FlakyBackfillRow[] = [];

    for (const row of backfill) {
        const liveDay = liveByDate.get(row.date);
        if (liveDay === undefined) {
            fromBackfill.push(row);
            continue;
        }
        overlapping++;
        for (const key of KEYS) {
            if (row[key] !== liveDay[key]) {
                disagreements.push({
                    date: row.date,
                    key,
                    backfill: row[key],
                    live: liveDay[key],
                });
            }
        }
    }

    // `makeDay`'s index is provisional: the rows are renumbered from their final
    // sorted position below, so a backfilled day that lands *after* live days
    // still gets the index its date earns.
    const days = sorted([
        ...fromBackfill.map((row, index) => makeDay(row, index)),
        ...live,
    ]).map((day, index) => ({ ...day, day: index }) as Day);

    return { days, backfilled: fromBackfill.length, overlapping, disagreements };
}
