/**
 * Bundles the CLI into `bin/fx-tests.js`.
 *
 * One esbuild call, no config file. `PLAN.md` §2 picks esbuild precisely so
 * that the build is a line rather than a directory, and the CLI's needs are
 * simpler than the pages': one entry point, Node platform, no minification.
 *
 * **Not minified, and no inlining of anything else.** The pages minify because
 * load time over the wire is what they are judged on; a local CLI is read from
 * disk and the only thing minification would cost is a readable stack trace
 * when something throws. Source maps are emitted for the same reason.
 *
 * ## Why the shipped entry is bundled at all
 *
 * The sources import each other with `.ts` extensions and rely on Node's
 * type-stripping, which is behind `--experimental-strip-types` on Node 22 and
 * prints a warning on every run. Neither is acceptable for something with a
 * `bin` entry, so the published artefact is plain JavaScript with the types
 * stripped ahead of time. `bin/fx-tests` (no extension) keeps the
 * no-build-step development loop working — see below.
 */

import { build } from 'esbuild';
import { chmod, mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const outFile = join(root, 'bin', 'fx-tests.js');

await mkdir(join(root, 'bin'), { recursive: true });

const result = await build({
    entryPoints: [join(root, 'cli', 'bin', 'fx-tests.ts')],
    outfile: outFile,
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node20',
    sourcemap: true,
    // Everything is first-party; there are no runtime dependencies to keep
    // external. If one ever appears, this is where it would be listed, and
    // leaving it out would silently inline someone else's package.
    external: [],
    banner: { js: '#!/usr/bin/env node' },
    logLevel: 'info',
});

if (result.errors.length > 0) {
    process.exitCode = 1;
} else {
    await chmod(outFile, 0o755);
}

/**
 * The development entry point: runs the TypeScript sources directly.
 *
 * `PLAN.md` §2 promises the edit-reload loop survives the introduction of a
 * build, and for the CLI that means `./bin/fx-tests` runs what is in `cli/`
 * right now — no rebuild between an edit and a run. The built `.js` next to it
 * is what `npm install -g` gets.
 *
 * Written by the build rather than checked in so that the two cannot drift:
 * they are generated from the same place, and the shebang wrapper is three
 * lines of shell that would otherwise be a file nobody remembers to update.
 */
const devEntry = join(root, 'bin', 'fx-tests');
await writeFile(
    devEntry,
    `#!/bin/sh
# Development entry point: runs the TypeScript sources directly, so an edit in
# cli/ takes effect with no rebuild. Generated by tools/build-cli.ts.
# The built, dependency-free artefact is bin/fx-tests.js next to this file.
exec node --experimental-strip-types --no-warnings=ExperimentalWarning \\
    "$(dirname "$0")/../cli/bin/fx-tests.ts" "$@"
`
);
await chmod(devEntry, 0o755);

console.log(`Built ${outFile}`);
console.log(`Wrote ${devEntry} (development entry point, runs cli/ sources directly)`);
